(library
 (name vterm_lib)
 (libraries unix)
 (foreign_stubs (language c)
  (names vterm term wrap sel acs sysbuf
         keyseq kitty_keyseq mouseseq
         vterm_stubs)
  (flags (:standard -std=c99 -D_XOPEN_SOURCE=600 -g -fsanitize=address,undefined)))
 (c_library_flags (-fsanitize=address,undefined)))
