(include_subdirs qualified)

(library
 (name rocqtui_lib)
 (libraries unix yojson re rocq-runtime.parsing rocq-runtime.clib rocq-runtime.gramlib
            rocq-runtime.lib coqide-server.protocol coqide-server.core
            rocq_compat vterm_lib)
 (foreign_stubs (language c) (names locale_stubs inotify_stubs term_stubs)))
