(* Probes the installed rocq-runtime API and emits a small compat
   module normalizing differences across Rocq versions.

   Rocq's META files set [version = "dev"] regardless of the actual
   installed version, so we can't rely on [ocamlfind query -format %v].
   Instead we feature-probe by trying to compile a snippet that
   references [Gramlib.Stream.Failure] — a constructor that exists in
   Rocq <= 9.1 (LStream.next raises) and is removed in 9.2+ (LStream.next
   returns ['a option]). *)

let probe_has_old_lstream_api () =
  let tmpdir = Filename.temp_file "rocq_compat_probe_" "" in
  Sys.remove tmpdir;
  Unix.mkdir tmpdir 0o700;
  let cleanup () =
    List.iter
      (fun name ->
        try Sys.remove (Filename.concat tmpdir name) with _ -> ())
      ["probe.ml"; "probe.cmi"; "probe.cmo"];
    try Unix.rmdir tmpdir with _ -> ()
  in
  let probe_path = Filename.concat tmpdir "probe.ml" in
  let oc = open_out probe_path in
  output_string oc "let _ : 'a = raise Gramlib.Stream.Failure\n";
  close_out oc;
  let cmd =
    Printf.sprintf
      "cd %s && ocamlfind ocamlc -c -package rocq-runtime.gramlib probe.ml \
       >/dev/null 2>&1"
      (Filename.quote tmpdir)
  in
  let rc = Sys.command cmd in
  cleanup ();
  rc = 0

let body_new_api =
  "(* Generated by discover.ml — do not edit. *)\n\
   let lstream_next = Gramlib.LStream.next\n"

let body_old_api =
  "(* Generated by discover.ml — do not edit. *)\n\
   let lstream_next kw_state stream =\n\
  \  try Some (Gramlib.LStream.next kw_state stream)\n\
  \  with Gramlib.Stream.Failure -> None\n"

let () =
  let out = Sys.argv.(1) in
  let body =
    if probe_has_old_lstream_api () then body_old_api else body_new_api
  in
  let oc = open_out out in
  output_string oc body;
  close_out oc
